version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependancy-name: "debian"
        update-types: ["version-update:semver-major"]
